# Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rcm-mdm-frontend-service
spec:
  selector:
    app: rcm-mdm-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
